apiVersion: v1
entries:
  connaisseur:
  - apiVersion: v2
    appVersion: 2.5.2
    created: "2022-03-25T13:44:04.224049134Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: fe7eaf75a7c467330bed7d9f02a6cb74eb19aa6a7c6db9e855d2229a96e107f5
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.3.2.tgz
    version: 1.3.2
  - apiVersion: v2
    appVersion: 2.5.1
    created: "2022-03-25T13:44:04.223028826Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 485ec3bb56e28ca92d479dd70f58302c099e879d52117c4e88fe01e6af880722
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.3.1.tgz
    version: 1.3.1
  - apiVersion: v2
    appVersion: 2.5.0
    created: "2022-03-25T13:44:04.222006818Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 2f9c1c618ac4ad9036b6697a5af8fa7c405b8f8ac87bd99228b2a6cb6db2e7c3
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    appVersion: 2.4.1
    created: "2022-03-25T13:44:04.22096601Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 0e43fc30de3927c62f10a66a5fb828f5209452b5a5496651788746ac975daa7b
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v2
    appVersion: 2.4.0
    created: "2022-03-25T13:44:04.219946002Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 0727c9dcfe25813dcbf690fee8d849d16d7fd7d053a0e683f956a8770b4c1d9f
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 2.3.0
    created: "2022-03-25T13:44:04.218903594Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 3fe6474b7c384c99ac5420932dc980c6d20f7887ce5903168162ddecaba5c7dd
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 2.2.1
    created: "2022-03-25T13:44:04.217888886Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 9571292a2478241008fa3e22e95bc65b36bc1313d623a3537ce496c72edd4fa3
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 2.2.0
    created: "2022-03-25T13:44:04.216336874Z"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 1e3f943e5569957d2c60d99f770c206cfe6297dd1f04c248f500c8156a9b2d23
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://sse-secure-systems.github.io/connaisseur/charts/connaisseur-1.0.0.tgz
    version: 1.0.0
generated: "2022-03-25T13:44:04.214060456Z"
