name: trivy vuln scan
description: 'action that runs trivy '
runs:
  using: "composite"
  steps:
    - name: Setup reports folder
      run: |
        mkdir trivy-reports
      shell: sh
    - name: Run Trivy on Image
      uses: aquasecurity/trivy-action@master
      with:
        input: ${{ github.sha }}_image.tar
        scan-type: "image"
        hide-progress: false
        format: "table"
        output: 'trivy-reports/image.txt'
        exit-code: "1"
        ignore-unfixed: false
        severity: "UNKNOWN,MEDIUM,HIGH,CRITICAL"
