name: integration test

on:
  workflow_call:
    inputs:
      image:
        description: "Workflow build image used for testing, i.e. registry + repository + tag"
        type: string
        required: false
        default: ""
      registry:
        description: "Workflow build registry used for testing"
        type: string
        required: false
        default: ""
      repo_owner:
        description: 'Name of repository owner, e.g. "inputs.repo_owner" for ghcr.io'
        type: string
        default: ""
      skip_integration_tests:
        description: "Want to skip running certain integration tests 'none', 'non-required', 'all'?"
        type: string
        required: false
        default: "none"
      cosign_public_key:
        description: "Cosign public key used for signing the build image"
        type: string
        required: false
        default: ""

permissions: {}

jobs:
  required:
    name: required
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      matrix:
        test_case:
          [
            "complexity",
            "regular",
            "cosign",
            "multi-cosigned",
            "rekor-cosigned",
            "namespace-val",
            "deployment",
            "pre-config",
            "other-ns",
          ]
    services:
      alerting-endpoint:
        image: securesystemsengineering/alerting-endpoint
        ports:
          - 56243:56243
    steps:
      - name: Checkout code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - name: Login with registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          image: ${{ inputs.image }}
          registry: ${{ inputs.registry }}
          repo_owner: ${{ inputs.repo_owner }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          cosign_public_key: ${{ inputs.cosign_public_key }}
          test_case: ${{ matrix.test_case }}

  non-required:
    name: non-required
    runs-on: ubuntu-latest
    if: inputs.skip_integration_tests != 'non-required'
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:
        test_case:
          [
            "load",
            "configured-cert",
            "upgrade",
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: ./.github/actions/integration-test
        name: Run test
        with:
          image: ${{ inputs.image }}
          registry: ${{ inputs.registry }}
          repo_owner: ${{ inputs.repo_owner }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          cosign_public_key: ${{ inputs.cosign_public_key }}
          test_case: ${{ matrix.test_case }}

  k8s-versions:
    name: k8s versions
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      matrix:
        k8s_version:
          [
            "v1.20",
            "v1.21",
            "v1.22",
            "v1.23",
            "v1.24",
            "v1.25",
            "v1.26",
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - name: Run test
        uses: ./.github/actions/integration-test
        with:
          image: ${{ inputs.image }}
          registry: ${{ inputs.registry }}
          repo_owner: ${{ inputs.repo_owner }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          cosign_public_key: ${{ inputs.cosign_public_key }}
          k8s_version: ${{ matrix.k8s_version }}

  k8s-legacy-versions:
    name: k8s legacy versions
    runs-on: ubuntu-18.04
    if: inputs.skip_integration_tests != 'non-required'
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:
        k8s_version:
          [
            "v1.16",
            "v1.17",
            "v1.18",
            "v1.19",
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - name: Run test
        uses: ./.github/actions/integration-test
        with:
          image: ${{ inputs.image }}
          registry: ${{ inputs.registry }}
          repo_owner: ${{ inputs.repo_owner }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          cosign_public_key: ${{ inputs.cosign_public_key }}
          k8s_version: ${{ matrix.k8s_version }}
