name: unit-test

on:
  workflow_call:

permissions: {}

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: python:3
    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Install
        run: |
          pip3 install -r requirements_dev.txt && pip3 install .
      - name: Test
        run: pytest --cov=connaisseur --cov-report=xml tests/
      - name: Upload
        uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2 # v3.1.3
        with:
          file: coverage.xml
