name: Build and Deploy Dev Documentation

on:
  push:
    branches:
      - develop

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Configure the git user
        run: |
          git config user.name "versioning_user"
          git config user.email "connaisseur@securesystems.dev"
      - name: Install dependencies
        run: |
          pip install -r docs/requirements_docs.txt
      - name: Deploy
        run: |
          mike deploy --push develop
